# Generated by Django 4.2.8 on 2024-04-27 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_resources', '0002_sermon_alter_discussionforum_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='members',
        ),
        migrations.AddField(
            model_name='ministry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ministries/images/'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministry',
            name='leader_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='leader_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='leader_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='short_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
