# Generated by Django 5.0.4 on 2024-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_resources', '0003_remove_ministry_members_ministry_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/images/'),
        ),
    ]
