# Generated by Django 5.0.4 on 2024-05-06 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_resources', '0005_address_userprofile_admission_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='course_subject_combination',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(default='', max_length=128, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_kenya_involvement',
            field=models.CharField(default='', max_length=256, verbose_name='FOCUS Kenya Involvement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=128, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='admission_year',
            field=models.PositiveIntegerField(default=2020, verbose_name='Admission Year'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='completion_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Completion Year'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Denomination'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='e_team',
            field=models.CharField(max_length=50, verbose_name='E-Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='event_resources.ministry'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '07xxxxxx' or '01xxxxxx'.", regex='^(07|01)\\d{8}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Userprofile/images/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_no',
            field=models.CharField(max_length=20, verbose_name='Admission No.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
