# Generated by Django 5.0.4 on 2024-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_resources', '0006_alter_userprofile_options_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(default='', max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='e_team',
            field=models.CharField(default='', max_length=50, verbose_name='E-Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='focus_kenya_involvement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
