# Generated by Django 5.0.6 on 2024-05-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_resources', '0007_alter_userprofile_county_alter_userprofile_e_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='video_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
