# Generated by Django 5.0.6 on 2024-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_resources', '0009_resourcecategory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='thumbnails/'),
        ),
    ]
