# Generated by Django 5.0.6 on 2024-06-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_bio'),
        ('event_resources', '0011_topic_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionforum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Magazine', 'Magazine'), ('Resource', 'Resource'), ('Official Documents', 'Official Documents')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.customuser'),
        ),
    ]
